dataset:
  NUM_WORKERS: 16
  BATCH_SIZE: 2
  dataset_name: "sevir"
  img_height: 384
  img_width: 384
  in_len: 25 
  out_len: 24 
  seq_len: 49 
  plot_stride: 2
  interval_real_time: 5
  sample_mode: "sequent"
  stride: 24 
  layout: "NTHWC"
  start_date: null
  train_val_split_date: [2019, 1, 1]
  train_test_split_date: [2019, 6, 1]
  end_date: null
  metrics_mode: "0"
  metrics_list: ['csi', 'pod', 'sucr', 'bias']
  threshold_list: [16, 74, 133, 160, 181, 219]
layout:
  in_len: 25
  out_len: 24
  layout: "NTHWC"
optim:
  total_batch_size: 32
  micro_batch_size: 2
  seed: 0
  method: "adamw"
  lr: 5.0e-4 
  wd: 0.0 
  gradient_clip_val: 1.0 
  max_epochs: 120 
  # scheduler
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 1e-4 #Obsolete with the modified OneCycleLR scheduler!
  warmup_min_lr_ratio: 0.0
  warmup_percentage: 0.15
  # early stopping
  early_stop: true
  early_stop_mode: "min"
  early_stop_patience: 20
  save_top_k: 1
logging:
  logging_prefix: "Cuboid_SEVIR"
  monitor_lr: true
  monitor_device: false
  track_grad_norm: -1 
  use_wandb: false 
trainer:
  check_val_every_n_epoch: 1
  log_step_ratio: 0.001 
  precision: 32 
vis:
  train_example_data_idx_list: [0, ]
  val_example_data_idx_list: [80, ]
  test_example_data_idx_list: [0,10,20,30,50,60,80,90,100,110,120,130,140,150,160,170,180,190,200,210,230,240,250,260,270,280,290,310,320,330]
  eval_example_only: false
  plot_stride: 2
model:
  input_shape: [25, 384, 384, 3] # see initial_upsample_kucuk_ir function in cuboid_transformer for upsampling operation!
  target_shape: [24, 384, 384, 1]
  base_units: 128
  scale_alpha: 1.0

  enc_depth: [1, 1]
  dec_depth: [1, 1]
  enc_use_inter_ffn: true 
  dec_use_inter_ffn: true
  dec_hierarchical_pos_embed: true 

  downsample: 2 
  downsample_type: "patch_merge" 
  upsample_type: "upsample" 

  num_global_vectors: 32 
  use_dec_self_global: true 
  dec_self_update_global: true
  use_dec_cross_global: true 
  use_global_vector_ffn: true 
  use_global_self_attn: false 
  separate_global_qkv: false 
  global_dim_ratio: 1

  self_pattern: "axial"
  cross_self_pattern: "axial"
  cross_pattern: "cross_1x1"
  dec_cross_last_n_frames: null

  attn_drop: 0.1
  proj_drop: 0.1
  ffn_drop: 0.1
  num_heads: 16 

  ffn_activation: "gelu"
  gated_ffn: true 
  norm_layer: "layer_norm"
  padding_type: "zeros"
  pos_embed_type: "t+h+w"
  use_relative_pos: true
  self_attn_use_final_proj: true
  dec_use_first_self_attn: false

  z_init_method: "zeros"
  checkpoint_level: 0

  initial_downsample_type: "stack_conv"
  initial_downsample_activation: "leaky"
  initial_downsample_stack_conv_num_layers: 3
  initial_downsample_stack_conv_dim_list: [16, 64, 128]
  initial_downsample_stack_conv_downscale_list: [3, 2, 2]
  initial_downsample_stack_conv_num_conv_list: [2, 2, 2]

  attn_linear_init_mode: "0"
  ffn_linear_init_mode: "0"
  conv_init_mode: "0"
  down_up_linear_init_mode: "0"
  norm_init_mode: "0"
